### ISSUE TITLE
About Datasets

### ISSUE THREAD

**Issue by Madeline-hyh** [ut-amrl/coda-devkit#16]
Thank you very much for your work and  I am very interested in this dataset, your paper mentioned that the dataset contains five different geographical locations, but I did not see the sequence with WXY in the data set DATA_REPORT document. I look forward to hearing from you.

**Comment by artzha** [comment]
Hi Madeline, thank you for your interest in CODa. To make sure I understand your question correctly, are you looking for a geographic location named WXY? In our dataset, we collect data in geographic locations SWY, GDC, WCP, GUAD, and UNB. I have attached a figure from our paper below with these geographic locations labeled by color.

![image](https://github.com/ut-amrl/coda-devkit/assets/8358704/ec2fee0a-7521-4895-9f18-5185ea9b5044)

**Comment by Madeline-hyh** [comment]
Thank you for your prompt reply，I got it.

**Comment by Madeline-hyh** [comment]
And I find another question: I cannot find 2d-box files. Could you please tell me whether this part of the label was not made? Thank you!

**Comment by artzha** [comment]
Currently, we only provide 3d bounding box annotations. If you would like to obtain **loose fitting 2d bounding boxes**, you can use the [3D to 2D bbox projection helper function](https://github.com/ut-amrl/coda-devkit/blob/0390aeefd29c4a404470d04226ddbd4cc0e79b6d/helpers/visualization.py#L245) 

This is the result of that function.
![2d_rect_cam0_20_3517](https://github.com/ut-amrl/coda-devkit/assets/8358704/e8e5b553-a311-45d5-b4ea-1d882d2ed8cb)

**Comment by Madeline-hyh** [comment]
OK，Thank you very much for your reply！

**Comment by g-ch** [comment]
Also thank you for providing such a good dataset! I tried to download the complete dataset but only found sequences [here](https://web.corral.tacc.utexas.edu/texasrobotics/web_CODa/sequences/), which take about 300 GB. I checked several sequences and it looked like they belong to the same location. Could you please share the way to download the rest data? I want to try a location with more pedestrians. Thank you!

> Thank you very much for your work and I am very interested in this dataset, your paper mentioned that the dataset contains five different geographical locations, but I did not see the sequence with WXY in the data set DATA_REPORT document. I look forward to hearing from you.

**Comment by g-ch** [comment]
Sorry for the misunderstanding. I found the document about places and traffic conditions [here](https://github.com/ut-amrl/coda-devkit/blob/main/docs/DATA_REPORT.md). The reason why the file is not as big as I expected is that the data for rgb-d cameras hasn't been release yet. But all the sequences have been released. 

> Also thank you for providing such a good dataset! I tried to download the complete dataset but only found sequences [here](https://web.corral.tacc.utexas.edu/texasrobotics/web_CODa/sequences/), which take about 300 GB. I checked several sequences and it looked like they belong to the same location. Could you please share the way to download the rest data? I want to try a location with more pedestrians. Thank you!
> 
> > Thank you very much for your work and I am very interested in this dataset, your paper mentioned that the dataset contains five different geographical locations, but I did not see the sequence with WXY in the data set DATA_REPORT document. I look forward to hearing from you.

**Comment by artzha** [comment]
Hi @g-ch , I'm glad that you were able to understand the place and traffic information using the data report. We plan to release the rgb-d camera data soon as an extension to the main dataset. When that happens, our team will share an update via the project website and texas data repository page.

**Comment by g-ch** [comment]
@artzha Thank you again for releasing the new version with RGBD data. I noticed that the 58 minutes of ground-truth annotations (3d bounding boxes and point cloud segmentation) are spread over different time slots of different sequences. Is there a time table/list showing which frames have annotations and which don't?

**Comment by artzha** [comment]
Hi @g-ch, we have a metadata `.json` file for each annotated sequence that lists all of the annotated frames for both 3D bounding boxes and point cloud segmentation for each sequence. This can be found in the `metadata` subdirectory. We describe the dictionary contents here: https://github.com/ut-amrl/coda-devkit/blob/main/docs/DATA_REPORT.md#metadata-format-and-usage-metadata

We also provide helper functions in the development kit for reading the annotated frames from the json file by annotation type and train/val/test split: https://github.com/ut-amrl/coda-devkit/blob/de979a7bc5e16811b1e21bfca40b2dbf52b7c381/helpers/metadata.py#L57

**Comment by g-ch** [comment]
> Hi @g-ch, we have a metadata `.json` file for each annotated sequence that lists all of the annotated frames for both 3D bounding boxes and point cloud segmentation for each sequence. This can be found in the `metadata` subdirectory. We describe the dictionary contents here: https://github.com/ut-amrl/coda-devkit/blob/main/docs/DATA_REPORT.md#metadata-format-and-usage-metadata
> 
> We also provide helper functions in the development kit for reading the annotated frames from the json file by annotation type and train/val/test split:
> 
> https://github.com/ut-amrl/coda-devkit/blob/de979a7bc5e16811b1e21bfca40b2dbf52b7c381/helpers/metadata.py#L57

Got it. Thank you!
